env:
  global:
  - secure: QYSoKqc5l+gmoPmk+gWhvoQLU2UVyRBx5VyyrPUGfbyLXRZ/TZQpdiRakcckr4hWGf8O2iZfgyWnc4axlukIVhlpBX6LdRmiSQG0HZWMElc9vRlQX4AVnYiF/B47WIPcWJs8Q/nnrAXNmyGZ6mT8lVDtENgr8OsNiRcMS7yCRJ90oViVSq9zCkEssfb1+1jDlF+mdOe6Bscwp5MoJbKiopcwV8avUIT8X5yC2xj8Kqa/6+v3sZDuJ30QWBgU5x3Ul1cIPbnJDFWzw4arS8DlgUV71oVTIPXOeMvue9E8LTz5u9+4RBwWEgQnR9QVAP7u3Ct5SXWLpPon7IYFluR0PcwpjXPpnSg9cGhN+dsbyel9B3GqyCFDRv7GC+J+swod2C6smNiEi38HdjnutAdsXwzQWUEM15FZPS6np8W+ofYZGqXbQ099XYMEBC2Cm0XBANt0ZeoFLbmTUc12y98dmJYYe0xKvMCGuF4HHhzjMxVqMWEwGMJgq0c47iynS8LMpM86Cujtt9uCu8nXelZ4K7uZEnn2sQsIjBKVAnwrVK06WpEy6ce8acidhVBplNPT2zQsitn5mWvrIHCbDxIfxQbfwTLTm0LZ9Pv3hWs8T/3VTfPGa3wG5Bhrt34rLMAt/cjrmH0qH//gWozSGqe/yOhA9VMQy2oUKO/gtjrfF+c=
os:
- linux
- osx
sudo: false
install:
  - echo "Build on $TRAVIS_OS_NAME"
  - if [[ "$TRAVIS_TAG" == v* ]]; then export BUILD_STR=""; else export BUILD_STR="dev"; fi
  - bash .ci/travis/install_python.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda build -q conda-recipe -c csdms
  - conda install -q sedflux --use-local -c csdms
script:
  - sedflux -h
after_success:
  - bash .ci/travis/deploy_to_anaconda.sh
