os:
- linux
- osx
sudo: false
install:
- echo "Build on $TRAVIS_OS_NAME"
- if [[ "$TRAVIS_TAG" == v* ]]; then export BUILD_STR=""; else export BUILD_STR="dev";
  fi
- bash .ci/travis/install_python.sh
- export PATH="$HOME/miniconda/bin:$PATH"
- conda build -q conda-recipe -c csdms
- conda install -q sedflux --use-local -c csdms
script:
- sedflux -h
after_success:
- bash .ci/travis/deploy_to_anaconda.sh
env:
  global:
    secure: T3auYTJPlCVizqKwN7G0yLE/ZthNp6pKxSwEf83Mt2z7cSFBu0cPZ9uCR4NTd2c4tZveJQSiDVM4bRy11xu4L87HkjleLxwzLpvE94T6FlFsEjCHWwCYMkuCVL0XjMzaQ0wmupwolsjYrWGyUQPgAPT5anfpYUo0A8Ps06XY3Pk=
