package:
  name: sedflux
  version: "2.1"

source:
  path: ..

requirements:
  build:
    - cmake
    - glib [osx]
  run:
    - glib [osx]

about:
  home: https://github.com/mcflugen/sedflux
  license: MIT
  license_file: LICENSE
  summary: A stratigraphic basin-filling model

build:
  string: {{ environ.get('BUILD_STR', '') }}
