package:
  name: sedflux
  version: "2.1.1"

source:
  path: ..

requirements:
  build:
    - cmake
    - gcc
    - pkgconfig-command [osx]
    - glib [osx]
  run:
    - libgcc
    - glib [osx]

test:
  commands:
  - sedflux -h

about:
  home: https://github.com/mcflugen/sedflux
  license: MIT
  license_file: LICENSE
  summary: A stratigraphic basin-filling model

build:
  string: {{ environ.get('BUILD_STR', '') }}
